name: Donut
version: .01
main: donutcodes.donut.Donut
api-version: 1.16
load: POSTWORLD
author: TeamDonut

commands:
  sbmenu:
    description: Testing the gui
    usage: /sbmenu
  randomnumber:
    description: Generates a random number!
    usage: /randomnumber