name: Donut
version: .02
main: donutcodes.donut.Donut
api-version: 1.16
load: POSTWORLD
author: TeamDonut

commands:
  sbmenu:
    description: Testing the gui
    usage: /sbmenu
  randomnumber:
    description: Generates a random number!
    usage: /randomnumber
  claimfancystick:
    description: gui with fancy stick item
    usage: /claimfancystick
  clearchat:
    description: Clears the chat!
    usage: /clearchat
  donutbroadcast:
    description: Broadcast custom
    usage: /donutbroadcast <message>
  crystal:
    description: used for diaglog
    usage: /crystal
  givegrapplinghook:
    description: gives a grappling hook
    usage: /givegrapplinghook